version: "3.9"

services:
  rental-command:
    build: .
    container_name: rental-command
    ports:
      - "8006:8006"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_DATA_MONGODB_URI_State=mongodb://mongodb_state:27017/state_db
      - SPRING_DATA_MONGODB_URI_Event=mongodb://mongodb_event_mic:27017/EventStore
    depends_on:
      - mongodb_state
      - mongodb_event_mic
      - kafka
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M
    networks: [ "microservices" ]

  zookeeper:
    image: 'bitnami/zookeeper:3.8.0'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - "./zookeeper:/zookeeper"

    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "2.0"
        reservations:
          memory: 256M
    networks: [ "microservices" ]



  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,INTERNAL://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "2.0"
        reservations:
          memory: 1G
    networks: [ "microservices" ]


  mongodb_state:
    image: docker.io/bitnami/mongodb:4.4
    restart: always
    container_name: microservices_state
    environment:
      MONGODB_ROOT_USER: admin
      MONGODB_ROOT_PASSWORD: admin
      MONGODB_DATABASE: "bikeState"
    volumes:
      - ./mongodb_data_container:/data/db
    ports:
      - "27017:27017"
    networks: [ "microservices" ]


  mongodb_event_mic:
      image: docker.io/bitnami/mongodb:4.4
      restart: always
      container_name: microservices_event
      environment:
        MONGODB_ROOT_USER: admin
        MONGODB_ROOT_PASSWORD: admin
        MONGODB_DATABASE: "EventStore"
      volumes:
        - ./mongodb_data_container:/data/db
      ports:
        - "27019:27017"
      deploy:
        resources:
          limits:
            memory: 1G
            cpus: "1.0"
          reservations:
            memory: 512M
      networks: [ "microservices" ]
networks:
  microservices:
    name: microservices